default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  port: 5432
  username: postgres
  password: <%= ENV['POSTGRES_PASSWORD'] %>

development:
  <<: *default
  database: docker_example_dev

test:
  <<: *default
  database: docker_example_test
 
 production:
  <<: *default
  database: your_production_db_name #CHANGE ME
